name: Diabetes
description: This is sample description
tags: []
symptoms: []
triggers: ''
severity: ''
duration: ''
biologicalFilters:
  ageRange: ''
  gender: ''
  medicalConditions: ''
  medications: ''
  familyHistory: ''
  lifestyle: ''
  pastHospitalizations: ''
response:
  explanation: ''
  suggestedSpecialist: ''
  careTips: []
