name: Convert YAML to CSV

on:
  push:
    paths:
      - "diseases/*.yaml"

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install pyyaml pydantic

      - name: Run YAML to CSV converter
        run: python scripts/convert_and_sync.py

      - name: Commit CSV back to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add diseases.csv
          git commit -m "🔄 Auto-update diseases.csv from YAML files" || echo "No changes to commit"
          git push
